# Generated by Django 5.2.4 on 2025-11-27 17:26

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=120)),
                ('announcement_image', models.ImageField(upload_to=jobs.models.discount_announcement_image_path)),
                ('announcement_text', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('announcement_date', models.DateTimeField()),
            ],
        ),
    ]
