# Generated by Django 5.2.4 on 2025-11-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sold',
            field=models.BooleanField(default=False),
        ),
    ]
