# Generated by Django 5.2.4 on 2025-11-27 17:26

import community.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_kampususer_department_alter_kampususer_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_name', models.CharField(max_length=150)),
                ('community_logo', models.ImageField(upload_to=community.models.community_logo_path)),
                ('community_agent', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('community_about_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=100)),
                ('announcement_shorttext', models.CharField(blank=True, max_length=120)),
                ('announcement_text', models.TextField()),
                ('announcement_date', models.DateTimeField()),
                ('announcement_image', models.ImageField(upload_to='')),
                ('announcement_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', related_query_name='announcements', to='community.community')),
            ],
        ),
    ]
