# Generated by Django 5.2.4 on 2025-11-24 01:14

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kampususer',
            managers=[
                ('objects', accounts.models.KampusUserManager()),
            ],
        ),
    ]
