# Generated by Django 5.2.4 on 2025-11-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_kampususer_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampususer',
            name='Profile_Picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
