# Generated by Django 5.2.4 on 2025-11-25 03:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kampususer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kampususer',
            name='Profile_Picture',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_profile_picture_path),
        ),
    ]
