# Generated by Django 5.2.4 on 2025-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_kampususer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampususer',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
