# Generated by Django 5.2.4 on 2025-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_kampususer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampususer',
            name='Department',
            field=models.CharField(default='Salata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kampususer',
            name='Faculty',
            field=models.CharField(default='Salata'),
            preserve_default=False,
        ),
    ]
