# Generated by Django 5.2.4 on 2025-11-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_kampususer_department_kampususer_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kampususer',
            name='Department',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='kampususer',
            name='Faculty',
            field=models.CharField(blank=True),
        ),
    ]
