# Generated by Django 5.2.4 on 2025-11-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_kampususer_department_alter_kampususer_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kampususer',
            options={'ordering': ['Username']},
        ),
    ]
