# Generated by Django 5.2.4 on 2025-11-28 12:28

import django.db.models.deletion
import job_intern.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_title', models.CharField(max_length=150)),
                ('intern_image', models.ImageField(blank=True, upload_to=job_intern.models.intern_announcement_image_path)),
                ('intern_text', models.TextField()),
                ('intern_contact', models.TextField()),
                ('intern_date', models.DateTimeField(auto_now=True)),
                ('intern_time', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')])),
                ('intern_remote', models.BooleanField(default=False)),
                ('intern_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_announcements', to='job_intern.internplace')),
            ],
        ),
    ]
