# Generated by Django 5.2.4 on 2025-11-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_intern', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internplace',
            old_name='place_name',
            new_name='intern_place',
        ),
    ]
