# Generated by Django 5.2.4 on 2025-11-28 18:57

import job_intern.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_intern', '0002_rename_place_name_internplace_intern_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internplace',
            old_name='intern_place',
            new_name='place_name',
        ),
        migrations.AddField(
            model_name='internannouncement',
            name='intern_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internplace',
            name='place_contact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internplace',
            name='place_image',
            field=models.ImageField(blank=True, upload_to=job_intern.models.intern_place_image_path),
        ),
        migrations.AddField(
            model_name='internplace',
            name='place_text',
            field=models.TextField(blank=True),
        ),
    ]
