# Generated by Django 5.2.4 on 2025-11-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_intern', '0003_rename_intern_place_internplace_place_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
            ],
        ),
    ]
