# Generated by Django 5.2.4 on 2025-11-30 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_intern', '0004_interncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='internannouncement',
            name='intern_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interns', to='job_intern.interncategory'),
        ),
    ]
