# Generated by Django 5.2.4 on 2025-11-27 17:26

import django.db.models.deletion
import lost_and_find_items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=150)),
                ('item_image', models.ImageField(blank=True, upload_to=lost_and_find_items.models.found_item_image_path)),
                ('item_text', models.TextField()),
                ('item_date', models.DateTimeField(auto_now=True)),
                ('item_found', models.BooleanField(default=True)),
                ('item_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
